[build]
  command = "npm ci && npm run build"
  publish = "css"

[build.environment]
  NODE_VERSION = "18.20.4"
  NPM_FLAGS = "--no-optional --legacy-peer-deps"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200